### ISSUE TITLE
mode does not change when using powerline

### ISSUE THREAD

**Issue by atanasj** [Nyquase/vi-mode#2]
The mode indicator does not change in my zsh prompt. I use powerline also. What am I doing wrong?

**Comment by Nyquase** [comment]
I'm not using powerline so I can't really help you D:

**Comment by VProfirov** [comment]
@Nyquase Can you tell us what are you using in order to get that *.png look? Thank you in advance!
P.S. My speculation: It looks to me like POWERLEVEL9K theme's RPROMPT_INDICATOR or something. :smile:

**Comment by Nyquase** [comment]
I'm not sure what you are mean by *.png look ?
If you mean the right prompt, I'm setting the RPS1 variable (you can also set RPROMPT)

**Comment by VProfirov** [comment]
1. By *.png look => [The png in the README](https://github.com/Nyquase/vi-mode/blob/master/screenshot.png)
2. I used POWERLEVEL9K and added vi-mode like:
`POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs history time vi_mode)`
into the .zshrc to achieve a similar look.

However, I can't find a way to set a "VISUAL" mode option as it switches between INSERT and NORMAL. It shows visual mode as INSERT.

On top of that, I aim to place it as MULTILINE_LAST_PROMPT and be RIGHT_ELEMENT, which might not be possible just with settings in .zshrc (I use 2 line prompt)

P.S. I didn't expect you to answer that quickly. I was about to clarify my previous comment :laughing: 

Can you share .zshrc that achieves that beautiful right-side vi-mode result with the VISUAL mode indicator?

**Comment by Nyquase** [comment]
Ah yes powerlevel9k doesn't support Visual mode by default, I don't remember exactly how but I was using poerlevel9k with my visual mode at some point, maybe you can take a look [here](https://github.com/Nyquase/powerlevel9k) (I forked powerlevel9k)

Edit: I believe it's more precisely here that I added the visual support https://github.com/Nyquase/powerlevel9k/blob/master/powerlevel9k.zsh-theme#L1629

Also you need to install https://github.com/b4b4r07/zsh-vimode-visual
